const recommendedCompanies = [
  {
    email: 'admin@gmail.com',
    password: 'pass1234@Admin',
    username: 'techcorp_admin',
    role: 'EMPLOYER',
    companyName: 'TechCorp',
    companySize: '100',
    websiteUrl: 'https://techcorp.com',
  },
  {
    email: 'admin1@nomadlist.com',
    password: 'hashed_password_1',
    username: 'nomad_admin',
    role: 'EMPLOYER',
    companyName: 'Nomad',
    companySize: '1-10',
    websiteUrl: 'https://nomadlist.com',
  },
  {
    email: 'admin2@dropbox.com',
    password: 'hashed_password_2',
    username: 'dropbox_admin',
    role: 'EMPLOYER',
    companyName: 'Dropbox',
    companySize: '501+',
    websiteUrl: 'https://dropbox.com',
  },
  {
    email: 'admin3@cryptoflow.com',
    password: 'hashed_password_3',
    username: 'cryptoflow_admin',
    role: 'EMPLOYER',
    companyName: 'CryptoFlow',
    companySize: '201-500',
    websiteUrl: 'https://cryptoflow.com',
  },
  {
    email: 'admin4@terraform.io',
    password: 'hashed_password_4',
    username: 'terraform_admin',
    role: 'EMPLOYER',
    companyName: 'Terraform',
    companySize: '51-200',
    websiteUrl: 'https://terraform.io',
  },
  {
    email: 'admin5@revolut.com',
    password: 'hashed_password_5',
    username: 'revolut_admin',
    role: 'EMPLOYER',
    companyName: 'Revolut',
    companySize: '201-500',
    websiteUrl: 'https://revolut.com',
  },
  {
    email: 'admin6@canva.com',
    password: 'hashed_password_6',
    username: 'canva_admin',
    role: 'EMPLOYER',
    companyName: 'Canva',
    companySize: '501+',
    websiteUrl: 'https://canva.com',
  },
  {
    email: 'admin7@classpass.com',
    password: 'hashed_password_7',
    username: 'classpass_admin',
    role: 'EMPLOYER',
    companyName: 'ClassPass',
    companySize: '51-200',
    websiteUrl: 'https://classpass.com',
  },
  {
    email: 'admin8@pitch.com',
    password: 'hashed_password_8',
    username: 'pitch_admin',
    role: 'EMPLOYER',
    companyName: 'Pitch',
    companySize: '11-50',
    websiteUrl: 'https://pitch.com',
  },
  {
    email: 'admin9@figma.com',
    password: 'hashed_password_9',
    username: 'figma_admin',
    role: 'EMPLOYER',
    companyName: 'Figma',
    companySize: '201-500',
    websiteUrl: 'https://figma.com',
  },
  {
    email: 'admin10@vercel.com',
    password: 'hashed_password_10',
    username: 'vercel_admin',
    role: 'EMPLOYER',
    companyName: 'Vercel',
    companySize: '51-200',
    websiteUrl: 'https://vercel.com',
  },
  {
    email: 'admin11@notion.so',
    password: 'hashed_password_11',
    username: 'notion_admin',
    role: 'EMPLOYER',
    companyName: 'Notion',
    companySize: '201-500',
    websiteUrl: 'https://notion.so',
  },
  {
    email: 'admin12@gitlab.com',
    password: 'hashed_password_12',
    username: 'gitlab_admin',
    role: 'EMPLOYER',
    companyName: 'GitLab',
    companySize: '501+',
    websiteUrl: 'https://gitlab.com',
  },
  {
    email: 'admin13@buffer.com',
    password: 'hashed_password_13',
    username: 'buffer_admin',
    role: 'EMPLOYER',
    companyName: 'Buffer',
    companySize: '11-50',
    websiteUrl: 'https://buffer.com',
  },
  {
    email: 'admin14@trello.com',
    password: 'hashed_password_14',
    username: 'trello_admin',
    role: 'EMPLOYER',
    companyName: 'Trello',
    companySize: '51-200',
    websiteUrl: 'https://trello.com',
  },
  {
    email: 'admin15@zapier.com',
    password: 'hashed_password_15',
    username: 'zapier_admin',
    role: 'EMPLOYER',
    companyName: 'Zapier',
    companySize: '201-500',
    websiteUrl: 'https://zapier.com',
  },
  {
    email: 'admin16@slack.com',
    password: 'hashed_password_16',
    username: 'slack_admin',
    role: 'EMPLOYER',
    companyName: 'Slack',
    companySize: '501+',
    websiteUrl: 'https://slack.com',
  },
  {
    email: 'admin17@klarna.com',
    password: 'hashed_password_17',
    username: 'klarna_admin',
    role: 'EMPLOYER',
    companyName: 'Klarna',
    companySize: '501+',
    websiteUrl: 'https://klarna.com',
  },
  {
    email: 'admin18@adobe.com',
    password: 'hashed_password_18',
    username: 'adobe_admin',
    role: 'EMPLOYER',
    companyName: 'Adobe',
    companySize: '501+',
    websiteUrl: 'https://adobe.com',
  },
  {
    email: 'admin19@linkedin.com',
    password: 'hashed_password_19',
    username: 'linkedin_admin',
    role: 'EMPLOYER',
    companyName: 'LinkedIn',
    companySize: '501+',
    websiteUrl: 'https://linkedin.com',
  },
  {
    email: 'admin20@spotify.com',
    password: 'hashed_password_20',
    username: 'spotify_admin',
    role: 'EMPLOYER',
    companyName: 'Spotify',
    companySize: '501+',
    websiteUrl: 'https://spotify.com',
  },
  {
    email: 'admin21@deepmind.com',
    password: 'hashed_password_21',
    username: 'deepmind_admin',
    role: 'EMPLOYER',
    companyName: 'DeepMind',
    companySize: '201-500',
    websiteUrl: 'https://deepmind.com',
  },
  {
    email: 'admin22@webflow.com',
    password: 'hashed_password_22',
    username: 'webflow_admin',
    role: 'EMPLOYER',
    companyName: 'Webflow',
    companySize: '51-200',
    websiteUrl: 'https://webflow.com',
  },
  {
    email: 'admin23@shopify.com',
    password: 'hashed_password_23',
    username: 'shopify_admin',
    role: 'EMPLOYER',
    companyName: 'Shopify',
    companySize: '501+',
    websiteUrl: 'https://shopify.com',
  },
  {
    email: 'admin24@dribbble.com',
    password: 'hashed_password_24',
    username: 'dribbble_admin',
    role: 'EMPLOYER',
    companyName: 'Dribbble',
    companySize: '51-200',
    websiteUrl: 'https://dribbble.com',
  },
  {
    email: 'admin25@behance.net',
    password: 'hashed_password_25',
    username: 'behance_admin',
    role: 'EMPLOYER',
    companyName: 'Behance',
    companySize: '201-500',
    websiteUrl: 'https://behance.net',
  },
  {
    email: 'admin26@twitter.com',
    password: 'hashed_password_26',
    username: 'twitter_admin',
    role: 'EMPLOYER',
    companyName: 'Twitter',
    companySize: '501+',
    websiteUrl: 'https://twitter.com',
  },
];

export default recommendedCompanies;
