import { Repository } from 'typeorm';
import { Company } from '../../companies/entities/company.entity';
import { User } from 'src/users/entities/user.entity';

export class CompaniesSeeder {
  constructor(
    private readonly companyRepository: Repository<Company>,
    private readonly users: User[],
  ) {}

  async run(): Promise<Company[]> {
    // Clear existing data
    await this.companyRepository.createQueryBuilder().delete().execute();

    // Filter only EMPLOYER users (first 26 users to cover all companies)
    const employerUsers = this.users.slice(0, 26);

    // Validate that we have enough EMPLOYER users with valid IDs
    if (employerUsers.length < 26 || employerUsers.some((user) => !user.id)) {
      throw new Error(
        'Insufficient or invalid EMPLOYER users for seeding companies',
      );
    }

    const companies: Partial<Company>[] = [
      {
        user_id: employerUsers[0].id,
        name: 'Nomad',
        email: 'contact@nomadlist.com',
        website_url: 'https://nomadlist.com',
        founded_date: '2014-01-01',
        employee_count: '1-10',
        hr_contact_name: 'HR Nomad',
        hr_contact_email: 'hr@nomadlist.com',
        industry: 'Business Service',
        headquarters_location: 'Paris, France',
        isActive: true,
        isVerified: false,
        culture_description:
          'Nomad is a company based in Paris, France, focused on digital innovation and community building.',
        tags: ['Business Service'],
      },
      {
        user_id: employerUsers[1].id,
        name: 'Dropbox',
        email: 'contact@dropbox.com',
        website_url: 'https://dropbox.com',
        founded_date: '2007-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Dropbox',
        hr_contact_email: 'hr@dropbox.com',
        industry: 'Cloud Storage',
        headquarters_location: 'San Francisco, USA',
        isActive: true,
        isVerified: false,
        culture_description:
          'Dropbox is a file hosting service based in San Francisco, USA, known for cloud storage solutions.',
        tags: ['Tech', 'Cloud Storage'],
      },
      {
        user_id: employerUsers[2].id,
        name: 'CryptoFlow',
        email: 'contact@cryptoflow.com',
        website_url: 'https://cryptoflow.com',
        founded_date: '2020-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR CryptoFlow',
        hr_contact_email: 'hr@cryptoflow.com',
        industry: 'Cryptocurrency',
        headquarters_location: 'New York, NY',
        isActive: true,
        isVerified: false,
        culture_description:
          'Next-generation cryptocurrency exchange with advanced trading.',
        tags: ['Crypto', 'Blockchain', 'Fintech'],
      },
      {
        user_id: employerUsers[3].id,
        name: 'Terraform',
        email: 'contact@terraform.io',
        website_url: 'https://terraform.io',
        founded_date: '2014-01-01',
        employee_count: '51-200',
        hr_contact_name: 'HR Terraform',
        hr_contact_email: 'hr@terraform.io',
        industry: 'Infrastructure',
        headquarters_location: 'Hamburg, Germany',
        isActive: true,
        isVerified: false,
        culture_description:
          'Terraform is a tech company in Hamburg, Germany, specializing in infrastructure as code.',
        tags: ['Tech', 'Infrastructure'],
      },
      {
        user_id: employerUsers[4].id,
        name: 'Revolut',
        email: 'contact@revolut.com',
        website_url: 'https://revolut.com',
        founded_date: '2015-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR Revolut',
        hr_contact_email: 'hr@revolut.com',
        industry: 'Financial Technology',
        headquarters_location: 'Madrid, Spain',
        isActive: true,
        isVerified: false,
        culture_description:
          'Revolut is a fintech company based in Madrid, Spain, offering banking and financial services.',
        tags: ['Fintech'],
      },
      {
        user_id: employerUsers[5].id,
        name: 'Canva',
        email: 'contact@canva.com',
        website_url: 'https://canva.com',
        founded_date: '2012-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Canva',
        hr_contact_email: 'hr@canva.com',
        industry: 'Design',
        headquarters_location: 'Ankara, Turkey',
        isActive: true,
        isVerified: false,
        culture_description:
          'Canva is a design platform based in Ankara, Turkey, empowering users to create visual content.',
        tags: ['Design', 'Tech'],
      },
      {
        user_id: employerUsers[6].id,
        name: 'ClassPass',
        email: 'contact@classpass.com',
        website_url: 'https://classpass.com',
        founded_date: '2013-01-01',
        employee_count: '51-200',
        hr_contact_name: 'HR ClassPass',
        hr_contact_email: 'hr@classpass.com',
        industry: 'Fitness',
        headquarters_location: 'Berlin, Germany',
        isActive: true,
        isVerified: false,
        culture_description:
          'ClassPass is a fitness platform based in Berlin, Germany, connecting users with workout classes.',
        tags: ['Fitness', 'Tech'],
      },
      {
        user_id: employerUsers[7].id,
        name: 'Pitch',
        email: 'contact@pitch.com',
        website_url: 'https://pitch.com',
        founded_date: '2018-01-01',
        employee_count: '11-50',
        hr_contact_name: 'HR Pitch',
        hr_contact_email: 'hr@pitch.com',
        industry: 'Productivity',
        headquarters_location: 'Berlin, Germany',
        isActive: true,
        isVerified: false,
        culture_description:
          'Pitch is a presentation software company based in Berlin, Germany, focused on collaborative tools.',
        tags: ['Tech', 'Productivity'],
      },
      {
        user_id: employerUsers[8].id,
        name: 'Figma',
        email: 'contact@figma.com',
        website_url: 'https://figma.com',
        founded_date: '2012-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR Figma',
        hr_contact_email: 'hr@figma.com',
        industry: 'Design',
        headquarters_location: 'New York, USA',
        isActive: true,
        isVerified: false,
        culture_description:
          'Figma is a collaborative design platform based in New York, USA, known for real-time design tools.',
        tags: ['Design', 'Tech'],
      },
      {
        user_id: employerUsers[9].id,
        name: 'Vercel',
        email: 'contact@vercel.com',
        website_url: 'https://vercel.com',
        founded_date: '2015-01-01',
        employee_count: '51-200',
        hr_contact_name: 'HR Vercel',
        hr_contact_email: 'hr@vercel.com',
        industry: 'Web Development',
        headquarters_location: 'Amsterdam, Netherlands',
        isActive: true,
        isVerified: false,
        culture_description:
          'Vercel is a platform for frontend developers based in Amsterdam, Netherlands, simplifying web deployment.',
        tags: ['Tech', 'Web Development'],
      },
      {
        user_id: employerUsers[10].id,
        name: 'Notion',
        email: 'contact@notion.so',
        website_url: 'https://notion.so',
        founded_date: '2016-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR Notion',
        hr_contact_email: 'hr@notion.so',
        industry: 'Productivity',
        headquarters_location: 'Toronto, Canada',
        isActive: true,
        isVerified: false,
        culture_description:
          'Notion is a productivity tool company based in Toronto, Canada, offering all-in-one workspace solutions.',
        tags: ['Tech', 'Productivity'],
      },
      {
        user_id: employerUsers[11].id,
        name: 'GitLab',
        email: 'contact@gitlab.com',
        website_url: 'https://gitlab.com',
        founded_date: '2011-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR GitLab',
        hr_contact_email: 'hr@gitlab.com',
        industry: 'DevOps',
        headquarters_location: 'Remote',
        isActive: true,
        isVerified: false,
        culture_description:
          'GitLab is a web-based DevOps lifecycle tool based remotely, providing a Git repository manager.',
        tags: ['Tech', 'DevOps'],
      },
      {
        user_id: employerUsers[12].id,
        name: 'Buffer',
        email: 'contact@buffer.com',
        website_url: 'https://buffer.com',
        founded_date: '2010-01-01',
        employee_count: '11-50',
        hr_contact_name: 'HR Buffer',
        hr_contact_email: 'hr@buffer.com',
        industry: 'Social Media',
        headquarters_location: 'London, UK',
        isActive: true,
        isVerified: false,
        culture_description:
          'Buffer is a social media management platform based in London, UK, simplifying content scheduling.',
        tags: ['Tech', 'Social Media'],
      },
      {
        user_id: employerUsers[13].id,
        name: 'Trello',
        email: 'contact@trello.com',
        website_url: 'https://trello.com',
        founded_date: '2011-01-01',
        employee_count: '51-200',
        hr_contact_name: 'HR Trello',
        hr_contact_email: 'hr@trello.com',
        industry: 'Productivity',
        headquarters_location: 'Rome, Italy',
        isActive: true,
        isVerified: false,
        culture_description:
          'Trello is a project management tool based in Rome, Italy, known for its Kanban boards.',
        tags: ['Tech', 'Productivity'],
      },
      {
        user_id: employerUsers[14].id,
        name: 'Zapier',
        email: 'contact@zapier.com',
        website_url: 'https://zapier.com',
        founded_date: '2011-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR Zapier',
        hr_contact_email: 'hr@zapier.com',
        industry: 'Automation',
        headquarters_location: 'Sydney, Australia',
        isActive: true,
        isVerified: false,
        culture_description:
          'Zapier is an automation platform based in Sydney, Australia, connecting apps for workflows.',
        tags: ['Tech', 'Automation'],
      },
      {
        user_id: employerUsers[15].id,
        name: 'Slack',
        email: 'contact@slack.com',
        website_url: 'https://slack.com',
        founded_date: '2009-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Slack',
        hr_contact_email: 'hr@slack.com',
        industry: 'Communication',
        headquarters_location: 'Lisbon, Portugal',
        isActive: true,
        isVerified: false,
        culture_description:
          'Slack is a communication platform based in Lisbon, Portugal, enhancing team collaboration.',
        tags: ['Tech', 'Communication'],
      },
      {
        user_id: employerUsers[16].id,
        name: 'Klarna',
        email: 'contact@klarna.com',
        website_url: 'https://klarna.com',
        founded_date: '2005-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Klarna',
        hr_contact_email: 'hr@klarna.com',
        industry: 'Financial Technology',
        headquarters_location: 'Stockholm, Sweden',
        isActive: true,
        isVerified: false,
        culture_description:
          'Klarna is a fintech company based in Stockholm, Sweden, offering buy-now-pay-later services.',
        tags: ['Fintech'],
      },
      {
        user_id: employerUsers[17].id,
        name: 'Adobe',
        email: 'contact@adobe.com',
        website_url: 'https://adobe.com',
        founded_date: '1982-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Adobe',
        hr_contact_email: 'hr@adobe.com',
        industry: 'Creative',
        headquarters_location: 'Tokyo, Japan',
        isActive: true,
        isVerified: false,
        culture_description:
          'Adobe is a software company based in Tokyo, Japan, known for creative and multimedia tools.',
        tags: ['Tech', 'Creative'],
      },
      {
        user_id: employerUsers[18].id,
        name: 'LinkedIn',
        email: 'contact@linkedin.com',
        website_url: 'https://linkedin.com',
        founded_date: '2003-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR LinkedIn',
        hr_contact_email: 'hr@linkedin.com',
        industry: 'Networking',
        headquarters_location: 'Dublin, Ireland',
        isActive: true,
        isVerified: false,
        culture_description:
          'LinkedIn is a professional networking platform based in Dublin, Ireland, connecting professionals.',
        tags: ['Tech', 'Networking'],
      },
      {
        user_id: employerUsers[19].id,
        name: 'Spotify',
        email: 'contact@spotify.com',
        website_url: 'https://spotify.com',
        founded_date: '2006-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Spotify',
        hr_contact_email: 'hr@spotify.com',
        industry: 'Music',
        headquarters_location: 'Oslo, Norway',
        isActive: true,
        isVerified: false,
        culture_description:
          'Spotify is a music streaming service based in Oslo, Norway, offering a vast library of audio content.',
        tags: ['Tech', 'Music'],
      },
      {
        user_id: employerUsers[20].id,
        name: 'DeepMind',
        email: 'contact@deepmind.com',
        website_url: 'https://deepmind.com',
        founded_date: '2010-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR DeepMind',
        hr_contact_email: 'hr@deepmind.com',
        industry: 'AI',
        headquarters_location: 'London, UK',
        isActive: true,
        isVerified: false,
        culture_description:
          'DeepMind is an AI research company based in London, UK, advancing artificial intelligence.',
        tags: ['Tech', 'AI'],
      },
      {
        user_id: employerUsers[21].id,
        name: 'Webflow',
        email: 'contact@webflow.com',
        website_url: 'https://webflow.com',
        founded_date: '2013-01-01',
        employee_count: '51-200',
        hr_contact_name: 'HR Webflow',
        hr_contact_email: 'hr@webflow.com',
        industry: 'Web Design',
        headquarters_location: 'San Francisco, USA',
        isActive: true,
        isVerified: false,
        culture_description:
          'Webflow is a web design platform based in San Francisco, CA, enabling no-code website creation.',
        tags: ['Tech', 'Web Design'],
      },
      {
        user_id: employerUsers[22].id,
        name: 'Shopify',
        email: 'contact@shopify.com',
        website_url: 'https://shopify.com',
        founded_date: '2006-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Shopify',
        hr_contact_email: 'hr@shopify.com',
        industry: 'E-commerce',
        headquarters_location: 'Remote',
        isActive: true,
        isVerified: false,
        culture_description:
          'Shopify is an e-commerce platform based remotely, empowering merchants to build online stores.',
        tags: ['Tech', 'E-commerce'],
      },
      {
        user_id: employerUsers[23].id,
        name: 'Dribbble',
        email: 'contact@dribbble.com',
        website_url: 'https://dribbble.com',
        founded_date: '2009-01-01',
        employee_count: '51-200',
        hr_contact_name: 'HR Dribbble',
        hr_contact_email: 'hr@dribbble.com',
        industry: 'Design',
        headquarters_location: 'Remote',
        isActive: true,
        isVerified: false,
        culture_description:
          'Dribbble is a design community based remotely, showcasing creative work and connecting designers.',
        tags: ['Design', 'Community'],
      },
      {
        user_id: employerUsers[24].id,
        name: 'Behance',
        email: 'contact@behance.net',
        website_url: 'https://behance.net',
        founded_date: '2005-01-01',
        employee_count: '201-500',
        hr_contact_name: 'HR Behance',
        hr_contact_email: 'hr@behance.net',
        industry: 'Design',
        headquarters_location: 'New York, USA',
        isActive: true,
        isVerified: false,
        culture_description:
          'Behance is a creative platform based in New York, NY, for showcasing and discovering creative work.',
        tags: ['Design', 'Creative'],
      },
      {
        user_id: employerUsers[25].id,
        name: 'Twitter',
        email: 'contact@twitter.com',
        website_url: 'https://twitter.com',
        founded_date: '2006-01-01',
        employee_count: '501+',
        hr_contact_name: 'HR Twitter',
        hr_contact_email: 'hr@twitter.com',
        industry: 'Social Media',
        headquarters_location: 'San Francisco, USA',
        isActive: true,
        isVerified: false,
        culture_description:
          'Twitter is a social media platform based in San Francisco, CA, connecting users through real-time updates.',
        tags: ['Tech', 'Social Media'],
      },
    ];

    const result = await this.companyRepository.save(companies);
    console.log(`✅ Seeded ${result.length} companies successfully.`);

    return result;
  }
}