import { Repository } from 'typeorm';

import { Company } from '../../companies/entities/company.entity';
import { User } from '../../users/entities/user.entity';
import { RoleENUM } from '../../roles/interface/roles.interface';
import { Job } from 'src/companies/entities/job.entity';

export class JobsSeeder {
  constructor(
    private readonly jobRepository: Repository<Job>,
    private readonly companyRepository: Repository<Company>,
    private readonly users: User[],
  ) {}

  async run(): Promise<Job[]> {
    // Filter EMPLOYER users (need at least 25 to cover all jobs)
    const employerUsers = this.users.filter(
      (user) => user.role.type === RoleENUM.EMPLOYER,
    );

    // Validate that we have enough EMPLOYER users
    if (employerUsers.length < 25 || employerUsers.some((user) => !user.id)) {
      throw new Error(
        'Insufficient or invalid EMPLOYER users for seeding jobs',
      );
    }

    // Fetch companies to associate with jobs
    const companies = await this.companyRepository.find();
    if (companies.length < 25) {
      throw new Error('Insufficient companies for seeding jobs');
    }

    const jobs: Partial<Job>[] = [
      // Existing jobs (24 jobs)
      {
        company_id:
          companies.find((c) => c.name === 'Nomad')?.id || companies[0].id,
        created_by: employerUsers[0].id,
        title: 'Senior Software Engineer',
        description:
          'Develop and maintain scalable web applications for Nomad.',
        responsibility: [
          'Design and implement APIs',
          'Optimize performance',
          'Collaborate with cross-functional teams',
        ],
        qualification: '5+ years of experience in software development',
        job_type: 'full-time',
        skill_required: 'JavaScript, TypeScript, Node.js',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 10,
        posted_at: '2025-06-01T00:00:00Z',
        expired_date: '2025-07-01T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Problem solver', 'Team player', 'Detail-oriented'],
        nice_to_haves: ['Experience with AWS', 'GraphQL knowledge'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          flexible_hours: 'Flexible work hours',
          remote_work: 'Fully remote option',
          stock_options: 'Equity package',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Nomad')?.id || companies[0].id,
        created_by: employerUsers[0].id,
        title: 'Frontend Developer',
        description: 'Build user-friendly interfaces for Nomad’s platforms.',
        responsibility: [
          'Develop UI components',
          'Ensure responsive design',
          'Collaborate with designers',
        ],
        qualification: '3+ years of experience with React',
        job_type: 'full-time',
        skill_required: 'React, CSS, HTML',
        salary_range: '$1500 - $2000',
        location: 'Remote',
        capacity: 8,
        posted_at: '2025-06-02T00:00:00Z',
        expired_date: '2025-07-02T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Creative', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: ['Experience with Next.js', 'TypeScript knowledge'],
        perks_benefits: {
          health_coverage: 'Full medical coverage',
          learning_stipend: '$2,000 annual learning budget',
          remote_work: 'Remote-first culture',
        },
        level: 'junior',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Nomad')?.id || companies[0].id,
        created_by: employerUsers[0].id,
        title: 'Social Media Assistant',
        description:
          'Manage and create content for Nomad’s social media platforms.',
        responsibility: [
          'Develop social media campaigns',
          'Engage with online communities',
          'Analyze performance metrics',
        ],
        qualification: '2+ years in social media marketing',
        job_type: 'part-time',
        skill_required: 'Social Media Marketing, Content Creation, Analytics',
        salary_range: '$500 - $1000',
        location: 'Paris, France',
        capacity: 10,
        posted_at: '2025-06-03T00:00:00Z',
        expired_date: '2025-07-03T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Creative', 'Communicative', 'Data-driven'],
        nice_to_haves: ['Experience with Hootsuite', 'Graphic design skills'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          flexible_hours: 'Flexible work hours',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Nomad')?.id || companies[0].id,
        created_by: employerUsers[0].id,
        title: 'Product Manager',
        description: 'Lead product development for Nomad’s digital platforms.',
        responsibility: [
          'Define product roadmaps',
          'Collaborate with engineering teams',
          'Gather user feedback',
        ],
        qualification: '4+ years in product management',
        job_type: 'full-time',
        skill_required: 'Product Management, Agile, UX',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 6,
        posted_at: '2025-06-04T00:00:00Z',
        expired_date: '2025-07-04T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Strategic', 'Collaborative', 'User-focused'],
        nice_to_haves: [
          'Experience with SaaS products',
          'Data analysis skills',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          remote_work: 'Fully remote',
        },
        level: 'senior level',
        tags: ['product', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Nomad')?.id || companies[0].id,
        created_by: employerUsers[0].id,
        title: 'Customer Success Specialist',
        description: 'Support Nomad’s community and ensure user satisfaction.',
        responsibility: [
          'Handle user inquiries',
          'Provide onboarding support',
          'Gather feedback',
        ],
        qualification: '2+ years in customer success',
        job_type: 'full-time',
        skill_required: 'Customer Service, CRM, Communication',
        salary_range: '$1000 - $1500',
        location: 'Paris, France',
        capacity: 8,
        posted_at: '2025-06-05T00:00:00Z',
        expired_date: '2025-07-05T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 3,
        who_you_are: ['Empathetic', 'Communicative', 'Organized'],
        nice_to_haves: ['Experience with Zendesk', 'Multilingual'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['support'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Dropbox')?.id || companies[1].id,
        created_by: employerUsers[1].id,
        title: 'Brand Designer',
        description: 'Create and maintain brand identity for Dropbox.',
        responsibility: [
          'Design brand assets',
          'Collaborate with marketing teams',
          'Ensure brand consistency',
        ],
        qualification: '3+ years in brand design',
        job_type: 'full-time',
        skill_required: 'Adobe Illustrator, Photoshop, Branding',
        salary_range: '$1500 - $2000',
        location: 'San Francisco, USA',
        capacity: 8,
        posted_at: '2025-06-06T00:00:00Z',
        expired_date: '2025-07-06T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Creative', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: [
          'Experience with motion graphics',
          'Knowledge of UI design',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          remote_work: 'Remote-first culture',
        },
        level: 'junior',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'CryptoFlow')?.id || companies[2].id,
        created_by: employerUsers[2].id,
        title: 'DevOps Engineer',
        description: 'Manage CI/CD pipelines and cloud infrastructure.',
        responsibility: [
          'Automate deployments',
          'Monitor systems',
          'Ensure scalability',
        ],
        qualification: '4+ years in DevOps or related field',
        job_type: 'full-time',
        skill_required: 'Docker, Kubernetes, AWS',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 5,
        posted_at: '2025-06-07T00:00:00Z',
        expired_date: '2025-07-07T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Proactive', 'Analytical', 'Team-oriented'],
        nice_to_haves: ['Terraform experience', 'CI/CD expertise'],
        perks_benefits: {
          health_coverage: 'Health and dental insurance',
          flexible_hours: 'Flexible schedule',
          stock_options: 'Stock options available',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Terraform')?.id || companies[3].id,
        created_by: employerUsers[3].id,
        title: 'Interactive Developer',
        description: 'Build interactive web applications in Hamburg, Germany.',
        responsibility: [
          'Develop interactive features',
          'Optimize user experience',
          'Collaborate with designers',
        ],
        qualification: '3+ years in web development',
        job_type: 'full-time',
        skill_required: 'JavaScript, React, WebGL',
        salary_range: '$1500 - $2000',
        location: 'Hamburg, Germany',
        capacity: 12,
        posted_at: '2025-06-08T00:00:00Z',
        expired_date: '2025-07-08T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 8,
        who_you_are: ['Innovative', 'Technical', 'Collaborative'],
        nice_to_haves: ['Experience with Three.js', 'Animation skills'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          learning_stipend: '$2,000 learning budget',
          flexible_hours: 'Flexible schedule',
        },
        level: 'junior',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Revolut')?.id || companies[4].id,
        created_by: employerUsers[4].id,
        title: 'Email Marketing Specialist',
        description:
          'Design and execute email marketing campaigns in Madrid, Spain.',
        responsibility: [
          'Create email campaigns',
          'Analyze campaign performance',
          'Segment audiences',
        ],
        qualification: '2+ years in email marketing',
        job_type: 'full-time',
        skill_required: 'Email Marketing, Mailchimp, Analytics',
        salary_range: '$1000 - $1500',
        location: 'Madrid, Spain',
        capacity: 10,
        posted_at: '2025-06-09T00:00:00Z',
        expired_date: '2025-07-09T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Creative', 'Analytical', 'Detail-oriented'],
        nice_to_haves: ['Experience with HubSpot', 'Copywriting skills'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          paid_time_off: '20 days PTO',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Canva')?.id || companies[5].id,
        created_by: employerUsers[5].id,
        title: 'Lead Engineer',
        description: 'Lead engineering team for Canva in Ankara Turkey.',
        responsibility: [
          'Lead technical projects',
          'Mentor junior engineers',
          'Ensure code quality',
        ],
        qualification: '6+ years in software engineering',
        job_type: 'full-time',
        skill_required: 'JavaScript, Node.js, Leadership',
        salary_range: '$3000 or above',
        location: 'Ankara, Turkey',
        capacity: 10,
        posted_at: '2025-06-10T00:00:00Z',
        expired_date: '2025-07-10T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Leader', 'Technical', 'Collaborative'],
        nice_to_haves: [
          'Experience with scalable systems',
          'Agile methodology',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          professional_development: '$3,000 learning stipend',
        },
        level: 'manager',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'ClassPass')?.id || companies[6].id,
        created_by: employerUsers[6].id,
        title: 'Product Designer',
        description:
          'Design user-centric products for ClassPass in Berlin, Germany.',
        responsibility: [
          'Create wireframes and prototypes',
          'Conduct user testing',
          'Collaborate with product managers',
        ],
        qualification: '4+ years in product design',
        job_type: 'full-time',
        skill_required: 'Figma, User Research, Prototyping',
        salary_range: '$1500 - $2000',
        location: 'Berlin, Germany',
        capacity: 10,
        posted_at: '2025-06-11T00:00:00Z',
        expired_date: '2025-07-11T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['User-focused', 'Creative', 'Collaborative'],
        nice_to_haves: ['Experience with mobile design', 'UX writing skills'],
        perks_benefits: {
          health_coverage: 'Health and vision insurance',
          flexible_hours: 'Flexible work hours',
          wellness_program: 'Wellness stipend',
        },
        level: 'senior level',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Pitch')?.id || companies[7].id,
        created_by: employerUsers[7].id,
        title: 'Customer Success Manager',
        description:
          'Manage customer relationships for Pitch in Berlin, Germany.',
        responsibility: [
          'Handle customer inquiries',
          'Build client relationships',
          'Collaborate with sales teams',
        ],
        qualification: '3+ years in customer success',
        job_type: 'full-time',
        skill_required: 'Customer Service, CRM, Communication',
        salary_range: '$1000 - $1500',
        location: 'Berlin, Germany',
        capacity: 10,
        posted_at: '2025-06-12T00:00:00Z',
        expired_date: '2025-07-12T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Empathetic', 'Communicative', 'Organized'],
        nice_to_haves: ['Experience with Salesforce', 'Multilingual'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          paid_time_off: '25 days PTO',
          team_retreats: 'Annual team retreats',
        },
        level: 'manager',
        tags: ['sales'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Figma')?.id || companies[8].id,
        created_by: employerUsers[8].id,
        title: 'UI/UX Designer',
        description: 'Design intuitive interfaces for Figma in New York, USA.',
        responsibility: [
          'Create UI designs',
          'Conduct user research',
          'Collaborate with developers',
        ],
        qualification: '3+ years in UI/UX design',
        job_type: 'full-time',
        skill_required: 'Figma, Sketch, User Research',
        salary_range: '$1500 - $2000',
        location: 'New York, USA',
        capacity: 7,
        posted_at: '2025-06-13T00:00:00Z',
        expired_date: '2025-07-13T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 3,
        who_you_are: ['Creative', 'User-focused', 'Collaborative'],
        nice_to_haves: ['Experience with prototyping', 'Animation skills'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          remote_work: 'Fully remote',
          learning_stipend: '$2,000 learning budget',
        },
        level: 'junior',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Vercel')?.id || companies[9].id,
        created_by: employerUsers[9].id,
        title: 'Frontend Developer',
        description:
          'Build scalable frontends for Vercel in Amsterdam, Netherlands.',
        responsibility: [
          'Develop UI components',
          'Optimize performance',
          'Collaborate with backend teams',
        ],
        qualification: '3+ years in frontend development',
        job_type: 'full-time',
        skill_required: 'React, Next.js, JavaScript',
        salary_range: '$1500 - $2000',
        location: 'Amsterdam, Netherlands',
        capacity: 9,
        posted_at: '2025-06-14T00:00:00Z',
        expired_date: '2025-07-14T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 4,
        who_you_are: ['Technical', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: ['Experience with Vercel', 'TypeScript knowledge'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          remote_work: 'Remote-first culture',
          stock_options: 'Equity package',
        },
        level: 'junior',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Notion')?.id || companies[10].id,
        created_by: employerUsers[10].id,
        title: 'Community Manager',
        description: 'Engage and grow Notion’s community in Toronto, Canada.',
        responsibility: [
          'Manage community platforms',
          'Organize events',
          'Gather feedback',
        ],
        qualification: '2+ years in community management',
        job_type: 'part-time',
        skill_required: 'Community Management, Communication, Event Planning',
        salary_range: '$500 - $1000',
        location: 'Toronto, Canada',
        capacity: 10,
        posted_at: '2025-06-15T00:00:00Z',
        expired_date: '2025-07-15T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 6,
        who_you_are: ['Engaging', 'Communicative', 'Organized'],
        nice_to_haves: ['Experience with Discord', 'Social media expertise'],
        perks_benefits: {
          health_coverage: 'Partial health coverage',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'GitLab')?.id || companies[11].id,
        created_by: employerUsers[11].id,
        title: 'DevOps Engineer',
        description: 'Manage CI/CD pipelines for GitLab in a remote setting.',
        responsibility: [
          'Automate deployments',
          'Monitor infrastructure',
          'Ensure scalability',
        ],
        qualification: '4+ years in DevOps',
        job_type: 'full-time',
        skill_required: 'Docker, Kubernetes, CI/CD',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 5,
        posted_at: '2025-06-16T00:00:00Z',
        expired_date: '2025-07-16T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Proactive', 'Technical', 'Collaborative'],
        nice_to_haves: ['Experience with GitLab CI', 'Cloud expertise'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          remote_work: 'Fully remote',
          learning_stipend: '$2,500 learning budget',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Buffer')?.id || companies[12].id,
        created_by: employerUsers[12].id,
        title: 'Content Writer',
        description: 'Create engaging content for Buffer in London, UK.',
        responsibility: [
          'Write blog posts',
          'Develop social media content',
          'Collaborate with marketing',
        ],
        qualification: '2+ years in content writing',
        job_type: 'part-time',
        skill_required: 'Copywriting, SEO, Content Creation',
        salary_range: '$500 - $1000',
        location: 'London, UK',
        capacity: 4,
        posted_at: '2025-06-17T00:00:00Z',
        expired_date: '2025-07-17T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 1,
        who_you_are: ['Creative', 'Detail-oriented', 'Communicative'],
        nice_to_haves: ['Experience with WordPress', 'Social media expertise'],
        perks_benefits: {
          health_coverage: 'Partial health coverage',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Remote-first culture',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Trello')?.id || companies[13].id,
        created_by: employerUsers[13].id,
        title: 'QA Tester',
        description: 'Ensure quality of Trello’s software in Rome, Italy.',
        responsibility: [
          'Test software features',
          'Report bugs',
          'Collaborate with developers',
        ],
        qualification: '2+ years in QA testing',
        job_type: 'full-time',
        skill_required: 'Testing, Bug Tracking, Automation',
        salary_range: '$1000 - $1500',
        location: 'Rome, Italy',
        capacity: 6,
        posted_at: '2025-06-18T00:00:00Z',
        expired_date: '2025-07-18T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 4,
        who_you_are: ['Detail-oriented', 'Analytical', 'Collaborative'],
        nice_to_haves: ['Experience with Selenium', 'Agile methodology'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          paid_time_off: '20 days PTO',
          learning_stipend: '$1,500 learning budget',
        },
        level: 'entry level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Zapier')?.id || companies[14].id,
        created_by: employerUsers[14].id,
        title: 'Growth Marketer',
        description: 'Drive growth strategies for Zapier in Sydney, Australia.',
        responsibility: [
          'Develop growth campaigns',
          'Analyze metrics',
          'Collaborate with product teams',
        ],
        qualification: '3+ years in growth marketing',
        job_type: 'full-time',
        skill_required: 'Growth Hacking, Analytics, Marketing',
        salary_range: '$1500 - $2000',
        location: 'Sydney, Australia',
        capacity: 10,
        posted_at: '2025-06-19T00:00:00Z',
        expired_date: '2025-07-19T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 3,
        who_you_are: ['Data-driven', 'Creative', 'Strategic'],
        nice_to_haves: ['Experience with SaaS', 'SEO expertise'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          remote_work: 'Remote-first culture',
          professional_development: '$2,000 learning stipend',
        },
        level: 'junior',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Slack')?.id || companies[15].id,
        created_by: employerUsers[15].id,
        title: 'Support Specialist',
        description: 'Provide customer support for Slack in Lisbon, Portugal.',
        responsibility: [
          'Handle support tickets',
          'Assist users',
          'Collaborate with product teams',
        ],
        qualification: '2+ years in customer support',
        job_type: 'full-time',
        skill_required: 'Customer Service, Communication, CRM',
        salary_range: '$500 - $1000',
        location: 'Lisbon, Portugal',
        capacity: 6,
        posted_at: '2025-06-20T00:00:00Z',
        expired_date: '2025-07-20T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Empathetic', 'Communicative', 'Organized'],
        nice_to_haves: ['Experience with Zendesk', 'Multilingual'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Fully remote',
        },
        level: 'entry level',
        tags: ['sales'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Klarna')?.id || companies[16].id,
        created_by: employerUsers[16].id,
        title: 'Data Analyst',
        description:
          'Analyze data to drive insights for Klarna in Stockholm, Sweden.',
        responsibility: [
          'Analyze datasets',
          'Create reports',
          'Collaborate with stakeholders',
        ],
        qualification: '3+ years in data analysis',
        job_type: 'full-time',
        skill_required: 'SQL, Python, Data Visualization',
        salary_range: '$1500 - $2000',
        location: 'Stockholm, Sweden',
        capacity: 10,
        posted_at: '2025-06-21T00:00:00Z',
        expired_date: '2025-07-21T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 7,
        who_you_are: ['Analytical', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: [
          'Experience with Tableau',
          'Machine learning knowledge',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          paid_time_off: '25 days PTO',
          wellness_program: 'Wellness stipend',
        },
        level: 'junior',
        tags: ['business', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Adobe')?.id || companies[17].id,
        created_by: employerUsers[17].id,
        title: 'Motion Designer',
        description: 'Create motion graphics for Adobe in Tokyo, Japan.',
        responsibility: [
          'Design animations',
          'Collaborate with creative teams',
          'Ensure brand consistency',
        ],
        qualification: '3+ years in motion design',
        job_type: 'full-time',
        skill_required: 'After Effects, Premiere Pro, Animation',
        salary_range: '$1500 - $2000',
        location: 'Tokyo, Japan',
        capacity: 8,
        posted_at: '2025-06-22T00:00:00Z',
        expired_date: '2025-07-22T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Creative', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: ['Experience with 3D animation', 'Storyboarding skills'],
        perks_benefits: {
          health_coverage: 'Health and vision insurance',
          flexible_hours: 'Flexible work hours',
          professional_development: '$2,000 learning stipend',
        },
        level: 'junior',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'LinkedIn')?.id || companies[18].id,
        created_by: employerUsers[18].id,
        title: 'Tech Recruiter',
        description: 'Recruit top talent for LinkedIn in Dublin, Ireland.',
        responsibility: [
          'Source candidates',
          'Conduct interviews',
          'Collaborate with hiring managers',
        ],
        qualification: '3+ years in technical recruiting',
        job_type: 'full-time',
        skill_required: 'Recruiting, HR, Communication',
        salary_range: '$1500 - $2000',
        location: 'Dublin, Ireland',
        capacity: 9,
        posted_at: '2025-06-23T00:00:00Z',
        expired_date: '2025-07-23T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 6,
        who_you_are: ['Communicative', 'Organized', 'Strategic'],
        nice_to_haves: [
          'Experience with tech hiring',
          'Knowledge of ATS systems',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          paid_time_off: '25 days PTO',
          team_retreats: 'Annual team retreats',
        },
        level: 'junior',
        tags: ['hr'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Spotify')?.id || companies[19].id,
        created_by: employerUsers[19].id,
        title: 'Mobile Developer',
        description: 'Develop mobile applications for Spotify in Oslo, Norway.',
        responsibility: [
          'Build mobile apps',
          'Optimize performance',
          'Collaborate with designers',
        ],
        qualification: '4+ years in mobile development',
        job_type: 'full-time',
        skill_required: 'Swift, Kotlin, Mobile Development',
        salary_range: '$3000 or above',
        location: 'Oslo, Norway',
        capacity: 10,
        posted_at: '2025-06-24T00:00:00Z',
        expired_date: '2025-07-24T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Technical', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: ['Experience with React Native', 'UI/UX knowledge'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          remote_work: 'Hybrid work options',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      // New jobs for Airtable (5 jobs)
      {
        company_id:
          companies.find((c) => c.name === 'Airtable')?.id || companies[20].id,
        created_by: employerUsers[20].id,
        title: 'Backend Engineer',
        description:
          'Develop and maintain backend systems for Airtable in San Francisco, USA.',
        responsibility: [
          'Build scalable APIs',
          'Optimize database performance',
          'Collaborate with frontend teams',
        ],
        qualification: '4+ years in backend development',
        job_type: 'full-time',
        skill_required: 'Node.js, GraphQL, PostgreSQL',
        salary_range: '$3000 or above',
        location: 'San Francisco, USA',
        capacity: 8,
        posted_at: '2025-06-25T00:00:00Z',
        expired_date: '2025-07-25T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Technical', 'Problem solver', 'Collaborative'],
        nice_to_haves: ['Experience with MongoDB', 'Microservices knowledge'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          remote_work: 'Hybrid work options',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Airtable')?.id || companies[20].id,
        created_by: employerUsers[20].id,
        title: 'Product Marketing Manager',
        description:
          'Drive product marketing strategies for Airtable in San Francisco, USA.',
        responsibility: [
          'Develop marketing campaigns',
          'Analyze market trends',
          'Collaborate with product teams',
        ],
        qualification: '4+ years in product marketing',
        job_type: 'full-time',
        skill_required: 'Marketing, Analytics, Communication',
        salary_range: '$1500 - $2000',
        location: 'San Francisco, USA',
        capacity: 6,
        posted_at: '2025-06-26T00:00:00Z',
        expired_date: '2025-07-26T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Strategic', 'Creative', 'Data-driven'],
        nice_to_haves: ['Experience with SaaS products', 'SEO expertise'],
        perks_benefits: {
          health_coverage: 'Health and dental insurance',
          paid_time_off: '20 days PTO',
          professional_development: '$2,000 learning stipend',
        },
        level: 'senior level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Airtable')?.id || companies[20].id,
        created_by: employerUsers[20].id,
        title: 'Technical Writer',
        description:
          'Create technical documentation for Airtable’s products in Remote.',
        responsibility: [
          'Write user guides',
          'Document APIs',
          'Collaborate with engineering teams',
        ],
        qualification: '2+ years in technical writing',
        job_type: 'part-time',
        skill_required: 'Technical Writing, Documentation, Communication',
        salary_range: '$500 - $1000',
        location: 'Remote',
        capacity: 5,
        posted_at: '2025-06-27T00:00:00Z',
        expired_date: '2025-07-27T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 1,
        who_you_are: ['Detail-oriented', 'Communicative', 'Technical'],
        nice_to_haves: ['Experience with Markdown', 'API documentation skills'],
        perks_benefits: {
          health_coverage: 'Partial health coverage',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Fully remote',
        },
        level: 'entry level',
        tags: ['documentation', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Airtable')?.id || companies[20].id,
        created_by: employerUsers[20].id,
        title: 'Security Engineer',
        description:
          'Ensure the security of Airtable’s platforms in San Francisco, USA.',
        responsibility: [
          'Conduct security audits',
          'Implement security measures',
          'Collaborate with DevOps teams',
        ],
        qualification: '5+ years in cybersecurity',
        job_type: 'full-time',
        skill_required: 'Cybersecurity, Penetration Testing, Cloud Security',
        salary_range: '$3000 or above',
        location: 'San Francisco, USA',
        capacity: 7,
        posted_at: '2025-06-28T00:00:00Z',
        expired_date: '2025-07-28T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Analytical', 'Proactive', 'Technical'],
        nice_to_haves: ['Experience with SOC2', 'Knowledge of compliance'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          wellness_program: 'Wellness stipend',
        },
        level: 'senior level',
        tags: ['engineering', 'security'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Airtable')?.id || companies[20].id,
        created_by: employerUsers[20].id,
        title: 'Customer Support Lead',
        description:
          'Lead the customer support team for Airtable in Remote.',
        responsibility: [
          'Manage support team',
          'Handle escalations',
          'Improve support processes',
        ],
        qualification: '4+ years in customer support leadership',
        job_type: 'full-time',
        skill_required: 'Customer Service, Leadership, CRM',
        salary_range: '$1500 - $2000',
        location: 'Remote',
        capacity: 6,
        posted_at: '2025-06-29T00:00:00Z',
        expired_date: '2025-07-29T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 3,
        who_you_are: ['Empathetic', 'Organized', 'Leader'],
        nice_to_haves: ['Experience with Intercom', 'Multilingual'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Fully remote',
        },
        level: 'manager',
        tags: ['support'],
      },
    ];

    // Save jobs to the database
    const savedJobs: Job[] = [];
    for (const jobData of jobs) {
      if (!jobData.company_id) {
        console.warn(`Skipping job "${jobData.title}" due to missing company.`);
        continue;
      }
      const job = this.jobRepository.create({
        company_id: jobData.company_id,
        created_by: jobData.created_by,
        title: jobData.title,
        description: jobData.description,
        responsibility: jobData.responsibility,
        qualification: jobData.qualification,
        job_type: jobData.job_type,
        skill_required: jobData.skill_required,
        salary_range: jobData.salary_range,
        location: jobData.location,
        capacity: jobData.capacity,
        posted_at: jobData.posted_at,
        expired_date: jobData.expired_date,
        is_visible: jobData.is_visible,
        views: jobData.views,
        applicant_applied: jobData.applicant_applied,
        who_you_are: jobData.who_you_are,
        nice_to_haves: jobData.nice_to_haves,
        perks_benefits: jobData.perks_benefits,
        level: jobData.level,
        tags: jobData.tags,
      });

      const saved = await this.jobRepository.save(job);
      savedJobs.push(saved);
    }

    console.log(`✅ Seeded ${savedJobs.length} jobs successfully.`);

    return savedJobs;
  }
}