import { Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { Company } from '../../companies/entities/company.entity';
import { User } from '../../users/entities/user.entity';
import { RoleENUM } from '../../roles/interface/roles.interface';
import { Job } from 'src/companies/entities/job.entity';

export class JobsSeeder {
  constructor(
    private readonly jobRepository: Repository<Job>,
    private readonly companyRepository: Repository<Company>,
    private readonly users: User[],
  ) {}

  async run(): Promise<Job[]> {
    // Filter EMPLOYER users (need at least 30 to cover all jobs)
    const employerUsers = this.users.filter(
      (user) => user.role.type === RoleENUM.EMPLOYER,
    );

    // Validate that we have enough EMPLOYER users
    if (employerUsers.length < 25 || employerUsers.some((user) => !user.id)) {
      throw new Error(
        'Insufficient or invalid EMPLOYER users for seeding jobs',
      );
    }

    // Fetch companies to associate with jobs
    const companies = await this.companyRepository.find();
    if (companies.length < 24) {
      throw new Error('Insufficient companies for seeding jobs');
    }

    const jobs: Partial<Job>[] = [
      {
        company_id: companies[0].id,
        created_by: employerUsers[0].id,
        title: 'Senior Software Engineer',
        description: 'Develop and maintain scalable web applications.',
        responsibility: [
          'Design and implement APIs',
          'Optimize performance',
          'Collaborate with cross-functional teams',
        ],
        qualification: '5+ years of experience in software development',
        job_type: 'full-time',
        skill_required: 'JavaScript, TypeScript, Node.js',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 10,
        posted_at: '2025-06-01T00:00:00Z',
        expired_date: '2025-07-01T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Problem solver', 'Team player', 'Detail-oriented'],
        nice_to_haves: ['Experience with AWS', 'GraphQL knowledge'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          flexible_hours: 'Flexible work hours',
          remote_work: 'Fully remote option',
          stock_options: 'Equity package',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id: companies[1].id,
        created_by: employerUsers[1].id,
        title: 'Frontend Developer',
        description: 'Build user-friendly interfaces for web applications.',
        responsibility: [
          'Develop UI components',
          'Ensure responsive design',
          'Collaborate with designers',
        ],
        qualification: '3+ years of experience with React',
        job_type: 'full-time',
        skill_required: 'React, CSS, HTML',
        salary_range: '$1500 - $2000',
        location: 'Remote',
        capacity: 8,
        posted_at: '2025-06-02T00:00:00Z',
        expired_date: '2025-07-02T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Creative', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: ['Experience with Next.js', 'TypeScript knowledge'],
        perks_benefits: {
          health_coverage: 'Full medical coverage',
          learning_stipend: '$2,000 annual learning budget',
          remote_work: 'Remote-first culture',
        },
        level: 'junior',
        tags: ['engineering', 'technology'],
      },
      {
        company_id: companies[2].id,
        created_by: employerUsers[2].id,
        title: 'DevOps Engineer',
        description: 'Manage CI/CD pipelines and cloud infrastructure.',
        responsibility: [
          'Automate deployments',
          'Monitor systems',
          'Ensure scalability',
        ],
        qualification: '4+ years in DevOps or related field',
        job_type: 'full-time',
        skill_required: 'Docker, Kubernetes, AWS',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 5,
        posted_at: '2025-06-03T00:00:00Z',
        expired_date: '2025-07-03T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Proactive', 'Analytical', 'Team-oriented'],
        nice_to_haves: ['Terraform experience', 'CI/CD expertise'],
        perks_benefits: {
          health_coverage: 'Health and dental insurance',
          flexible_hours: 'Flexible schedule',
          stock_options: 'Stock options available',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id: companies[3].id,
        created_by: employerUsers[3].id,
        title: 'Renewable Energy Analyst',
        description: 'Analyze energy data to improve efficiency.',
        responsibility: [
          'Conduct energy audits',
          'Develop sustainability plans',
          'Collaborate with engineers',
        ],
        qualification: '3+ years in energy analysis',
        job_type: 'full-time',
        skill_required: 'Data analysis, Energy modeling',
        salary_range: '$1500 - $2000',
        location: 'San Francisco, USA',
        capacity: 8,
        posted_at: '2025-06-04T00:00:00Z',
        expired_date: '2025-07-04T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: [
          'Analytical',
          'Environmentally conscious',
          'Detail-oriented',
        ],
        nice_to_haves: [
          'Experience with solar energy systems',
          'Certification in energy management',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health plans',
          paid_time_off: '30 days PTO',
          wellness_program: 'Wellness stipend',
        },
        level: 'junior',
        tags: ['business'],
      },
      {
        company_id: companies[4].id,
        created_by: employerUsers[4].id,
        title: 'Cloud Solutions Architect',
        description: 'Design cloud-based solutions for enterprise clients.',
        responsibility: [
          'Architect cloud infrastructure',
          'Optimize cloud costs',
          'Ensure security',
        ],
        qualification: '5+ years in cloud architecture',
        job_type: 'full-time',
        skill_required: 'AWS, Azure, Cloud Security',
        salary_range: '$3000 or above',
        location: 'Seattle, USA',
        capacity: 6,
        posted_at: '2025-06-05T00:00:00Z',
        expired_date: '2025-07-05T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Innovative', 'Strategic thinker', 'Collaborative'],
        nice_to_haves: [
          'AWS Certified Solutions Architect',
          'Experience with microservices',
        ],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          professional_development: '$3,000 learning stipend',
          remote_work: 'Remote work options',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id: companies[5].id,
        created_by: employerUsers[5].id,
        title: 'Senior UX Designer',
        description: 'Design intuitive user experiences for digital products.',
        responsibility: [
          'Create wireframes',
          'Conduct user research',
          'Collaborate with developers',
        ],
        qualification: '4+ years in UX design',
        job_type: 'full-time',
        skill_required: 'Figma, Sketch, User Research',
        salary_range: '$1500 - $2000',
        location: 'New York, USA',
        capacity: 7,
        posted_at: '2025-06-06T00:00:00Z',
        expired_date: '2025-07-06T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Creative', 'User-focused', 'Collaborative'],
        nice_to_haves: ['Experience with motion design', 'Prototyping skills'],
        perks_benefits: {
          health_coverage: 'Health and vision insurance',
          flexible_hours: 'Flexible work hours',
          team_retreats: 'Annual team retreats',
        },
        level: 'senior level',
        tags: ['design'],
      },
      {
        company_id: companies[6].id,
        created_by: employerUsers[6].id,
        title: 'Graphic Designer',
        description: 'Create visually stunning designs for branding.',
        responsibility: [
          'Design logos',
          'Develop marketing materials',
          'Collaborate with creative team',
        ],
        qualification: '3+ years in graphic design',
        job_type: 'part-time',
        skill_required: 'Adobe Illustrator, Photoshop',
        salary_range: '$500 - $1000',
        location: 'London, UK',
        capacity: 5,
        posted_at: '2025-06-07T00:00:00Z',
        expired_date: '2025-07-07T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Creative', 'Detail-oriented', 'Team player'],
        nice_to_haves: ['Experience with branding', 'Animation skills'],
        perks_benefits: {
          health_coverage: 'Partial health coverage',
          flexible_hours: 'Flexible schedule',
        },
        level: 'junior',
        tags: ['design'],
      },
      {
        company_id: companies[7].id,
        created_by: employerUsers[7].id,
        title: 'Backend Engineer - Payments',
        description: 'Build and maintain payment processing systems.',
        responsibility: [
          'Develop payment APIs',
          'Ensure transaction security',
          'Optimize performance',
        ],
        qualification: '5+ years in backend development',
        job_type: 'full-time',
        skill_required: 'Node.js, Python, SQL',
        salary_range: '$3000 or above',
        location: 'San Francisco, USA',
        capacity: 6,
        posted_at: '2025-06-08T00:00:00Z',
        expired_date: '2025-07-08T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Analytical', 'Security-focused', 'Team-oriented'],
        nice_to_haves: [
          'Experience with payment gateways',
          'Knowledge of blockchain',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          remote_work: 'Remote-first culture',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id: companies[8].id,
        created_by: employerUsers[8].id,
        title: 'Site Reliability Engineer',
        description: 'Ensure high availability of hosting platforms.',
        responsibility: [
          'Monitor systems',
          'Automate infrastructure',
          'Handle incidents',
        ],
        qualification: '4+ years in SRE or DevOps',
        job_type: 'full-time',
        skill_required: 'Linux, Docker, Kubernetes',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 5,
        posted_at: '2025-06-09T00:00:00Z',
        expired_date: '2025-07-09T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Proactive', 'Problem solver', 'Collaborative'],
        nice_to_haves: ['Experience with Vercel', 'Monitoring tools expertise'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          learning_stipend: '$2,500 learning budget',
          remote_work: 'Remote work options',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id: companies[9].id,
        created_by: employerUsers[9].id,
        title: 'Management Consultant',
        description:
          'Provide strategic advice to improve business performance.',
        responsibility: [
          'Analyze business processes',
          'Develop strategies',
          'Client engagement',
        ],
        qualification: '5+ years in consulting',
        job_type: 'full-time',
        skill_required: 'Strategic planning, Data analysis',
        salary_range: '$3000 or above',
        location: 'New York, USA',
        capacity: 8,
        posted_at: '2025-06-10T00:00:00Z',
        expired_date: '2025-07-10T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Strategic thinker', 'Client-focused', 'Analytical'],
        nice_to_haves: ['MBA', 'Experience in Fortune 500 consulting'],
        perks_benefits: {
          health_coverage: 'Premium health insurance',
          professional_development: '$5,000 annual training budget',
          paid_time_off: '25 days PTO',
        },
        level: 'manager',
        tags: ['business'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Nomad')?.id || companies[10].id,
        created_by: employerUsers[10].id,
        title: 'Social Media Assistant',
        description:
          'Manage and create content for social media platforms in Paris, France.',
        responsibility: [
          'Develop social media campaigns',
          'Engage with online communities',
          'Analyze performance metrics',
        ],
        qualification: '2+ years in social media marketing',
        job_type: 'full-time',
        skill_required: 'Social Media Marketing, Content Creation, Analytics',
        salary_range: '$500 - $1000',
        location: 'Paris, France',
        capacity: 10,
        posted_at: '2025-06-11T00:00:00Z',
        expired_date: '2025-07-11T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Creative', 'Communicative', 'Data Stew-driven'],
        nice_to_haves: ['Experience with Hootsuite', 'Graphic design skills'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          flexible_hours: 'Flexible work hours',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Dropbox')?.id || companies[11].id,
        created_by: employerUsers[11].id,
        title: 'Brand Designer',
        description:
          'Create and maintain brand identity for Dropbox in San Francisco, USA.',
        responsibility: [
          'Design brand assets',
          'Collaborate with marketing teams',
          'Ensure brand consistency',
        ],
        qualification: '3+ years in brand design',
        job_type: 'full-time',
        skill_required: 'Adobe Illustrator, Photoshop, Branding',
        salary_range: '$1500 - $2000',
        location: 'San Francisco, USA',
        capacity: 8,
        posted_at: '2025-06-12T00:00:00Z',
        expired_date: '2025-07-12T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Creative', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: [
          'Experience with motion graphics',
          'Knowledge of UI design',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          remote_work: 'Remote-first culture',
        },
        level: 'junior',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Terraform')?.id || companies[12].id,
        created_by: employerUsers[12].id,
        title: 'Interactive Developer',
        description: 'Build interactive web applications in Hamburg, Germany.',
        responsibility: [
          'Develop interactive features',
          'Optimize user experience',
          'Collaborate with designers',
        ],
        qualification: '3+ years in web development',
        job_type: 'full-time',
        skill_required: 'JavaScript, React, WebGL',
        salary_range: '$1500 - $2000',
        location: 'Hamburg, Germany',
        capacity: 12,
        posted_at: '2025-06-13T00:00:00Z',
        expired_date: '2025-07-13T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 8,
        who_you_are: ['Innovative', 'Technical', 'Collaborative'],
        nice_to_haves: ['Experience with Three.js', 'Animation skills'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          learning_stipend: '$2,000 learning budget',
          flexible_hours: 'Flexible schedule',
        },
        level: 'junior',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Revolut')?.id || companies[13].id,
        created_by: employerUsers[13].id,
        title: 'Email Marketing',
        description:
          'Design and execute email marketing campaigns in Madrid, Spain.',
        responsibility: [
          'Create email campaigns',
          'Analyze campaign performance',
          'Segment audiences',
        ],
        qualification: '2+ years in email marketing',
        job_type: 'full-time',
        skill_required: 'Email Marketing, Mailchimp, Analytics',
        salary_range: '$1000 - $1500',
        location: 'Madrid, Spain',
        capacity: 10,
        posted_at: '2025-06-14T00:00:00Z',
        expired_date: '2025-07-14T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 0,
        who_you_are: ['Creative', 'Analytical', 'Detail-oriented'],
        nice_to_haves: ['Experience with HubSpot', 'Copywriting skills'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          paid_time_off: '20 days PTO',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Canva')?.id || companies[14].id,
        created_by: employerUsers[14].id,
        title: 'Lead Engineer',
        description: 'Lead engineering team for Canva in Ankara, Turkey.',
        responsibility: [
          'Lead technical projects',
          'Mentor junior engineers',
          'Ensure code quality',
        ],
        qualification: '6+ years in software engineering',
        job_type: 'full-time',
        skill_required: 'JavaScript, Node.js, Leadership',
        salary_range: '$3000 or above',
        location: 'Ankara, Turkey',
        capacity: 10,
        posted_at: '2025-06-15T00:00:00Z',
        expired_date: '2025-07-15T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Leader', 'Technical', 'Collaborative'],
        nice_to_haves: [
          'Experience with scalable systems',
          'Agile methodology',
        ],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          stock_options: 'Equity package',
          professional_development: '$3,000 learning stipend',
        },
        level: 'manager',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'ClassPass')?.id || companies[15].id,
        created_by: employerUsers[15].id,
        title: 'Product Designer',
        description:
          'Design user-centric products for ClassPass in Berlin, Germany.',
        responsibility: [
          'Create wireframes and prototypes',
          'Conduct user testing',
          'Collaborate with product managers',
        ],
        qualification: '4+ years in product design',
        job_type: 'full-time',
        skill_required: 'Figma, User Research, Prototyping',
        salary_range: '$1500 - $2000',
        location: 'Berlin, Germany',
        capacity: 10,
        posted_at: '2025-06-16T00:00:00Z',
        expired_date: '2025-07-16T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['User-focused', 'Creative', 'Collaborative'],
        nice_to_haves: ['Experience with mobile design', 'UX writing skills'],
        perks_benefits: {
          health_coverage: 'Health and vision insurance',
          flexible_hours: 'Flexible work hours',
          wellness_program: 'Wellness stipend',
        },
        level: 'senior level',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Pitch')?.id || companies[16].id,
        created_by: employerUsers[16].id,
        title: 'Customer Manager',
        description:
          'Manage customer relationships for Pitch in Berlin, Germany.',
        responsibility: [
          'Handle customer inquiries',
          'Build client relationships',
          'Collaborate with sales teams',
        ],
        qualification: '3+ years in customer success',
        job_type: 'full-time',
        skill_required: 'Customer Service, CRM, Communication',
        salary_range: '$1000 - $1500',
        location: 'Berlin, Germany',
        capacity: 10,
        posted_at: '2025-06-17T00:00:00Z',
        expired_date: '2025-07-17T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 5,
        who_you_are: ['Empathetic', 'Communicative', 'Organized'],
        nice_to_haves: ['Experience with Salesforce', 'Multilingual'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          paid_time_off: '25 days PTO',
          team_retreats: 'Annual team retreats',
        },
        level: 'manager',
        tags: ['sales'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Figma')?.id || companies[17].id,
        created_by: employerUsers[17].id,
        title: 'UI/UX Designer',
        description: 'Design intuitive interfaces for Figma in New York, USA.',
        responsibility: [
          'Create UI designs',
          'Conduct user research',
          'Collaborate with developers',
        ],
        qualification: '3+ years in UI/UX design',
        job_type: 'full-time',
        skill_required: 'Figma, Sketch, User Research',
        salary_range: '$1500 - $2000',
        location: 'New York, USA',
        capacity: 7,
        posted_at: '2025-06-18T00:00:00Z',
        expired_date: '2025-07-18T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 3,
        who_you_are: ['Creative', 'User-focused', 'Collaborative'],
        nice_to_haves: ['Experience with prototyping', 'Animation skills'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          remote_work: 'Fully remote',
          learning_stipend: '$2,000 learning budget',
        },
        level: 'junior',
        tags: ['design'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Vercel')?.id || companies[18].id,
        created_by: employerUsers[18].id,
        title: 'Frontend Developer',
        description:
          'Build scalable frontends for Vercel in Amsterdam, Netherlands.',
        responsibility: [
          'Develop UI components',
          'Optimize performance',
          'Collaborate with backend teams',
        ],
        qualification: '3+ years in frontend development',
        job_type: 'full-time',
        skill_required: 'React, Next.js, JavaScript',
        salary_range: '$1500 - $2000',
        location: 'Amsterdam, Netherlands',
        capacity: 9,
        posted_at: '2025-06-19T00:00:00Z',
        expired_date: '2025-07-19T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 4,
        who_you_are: ['Technical', 'Detail-oriented', 'Collaborative'],
        nice_to_haves: ['Experience with Vercel', 'TypeScript knowledge'],
        perks_benefits: {
          health_coverage: 'Full health coverage',
          remote_work: 'Remote-first culture',
          stock_options: 'Equity package',
        },
        level: 'junior',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Notion')?.id || companies[19].id,
        created_by: employerUsers[19].id,
        title: 'Community Manager',
        description: 'Engage and grow Notion’s community in Toronto, Canada.',
        responsibility: [
          'Manage community platforms',
          'Organize events',
          'Gather feedback',
        ],
        qualification: '2+ years in community management',
        job_type: 'part-time',
        skill_required: 'Community Management, Communication, Event Planning',
        salary_range: '$500 - $1000',
        location: 'Toronto, Canada',
        capacity: 10,
        posted_at: '2025-06-20T00:00:00Z',
        expired_date: '2025-07-20T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 6,
        who_you_are: ['Engaging', 'Communicative', 'Organized'],
        nice_to_haves: ['Experience with Discord', 'Social media expertise'],
        perks_benefits: {
          health_coverage: 'Partial health coverage',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Hybrid work options',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'GitLab')?.id || companies[20].id,
        created_by: employerUsers[20].id,
        title: 'DevOps Engineer',
        description: 'Manage CI/CD pipelines for GitLab in a remote setting.',
        responsibility: [
          'Automate deployments',
          'Monitor infrastructure',
          'Ensure scalability',
        ],
        qualification: '4+ years in DevOps',
        job_type: 'full-time',
        skill_required: 'Docker, Kubernetes, CI/CD',
        salary_range: '$3000 or above',
        location: 'Remote',
        capacity: 5,
        posted_at: '2025-06-21T00:00:00Z',
        expired_date: '2025-07-21T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 2,
        who_you_are: ['Proactive', 'Technical', 'Collaborative'],
        nice_to_haves: ['Experience with GitLab CI', 'Cloud expertise'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          remote_work: 'Fully remote',
          learning_stipend: '$2,500 learning budget',
        },
        level: 'senior level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Buffer')?.id || companies[21].id,
        created_by: employerUsers[21].id,
        title: 'Content Writer',
        description: 'Create engaging content for Buffer in London, UK.',
        responsibility: [
          'Write blog posts',
          'Develop social media content',
          'Collaborate with marketing',
        ],
        qualification: '2+ years in content writing',
        job_type: 'part-time',
        skill_required: 'Copywriting, SEO, Content Creation',
        salary_range: '$500 - $1000',
        location: 'London, UK',
        capacity: 4,
        posted_at: '2025-06-22T00:00:00Z',
        expired_date: '2025-07-22T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 1,
        who_you_are: ['Creative', 'Detail-oriented', 'Communicative'],
        nice_to_haves: ['Experience with WordPress', 'Social media expertise'],
        perks_benefits: {
          health_coverage: 'Partial health coverage',
          flexible_hours: 'Flexible schedule',
          remote_work: 'Remote-first culture',
        },
        level: 'entry level',
        tags: ['marketing'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Trello')?.id || companies[22].id,
        created_by: employerUsers[22].id,
        title: 'QA Tester',
        description: 'Ensure quality of Trello’s software in Rome, Italy.',
        responsibility: [
          'Test software features',
          'Report bugs',
          'Collaborate with developers',
        ],
        qualification: '2+ years in QA testing',
        job_type: 'full-time',
        skill_required: 'Testing, Bug Tracking, Automation',
        salary_range: '$1000 - $1500',
        location: 'Rome, Italy',
        capacity: 6,
        posted_at: '2025-06-23T00:00:00Z',
        expired_date: '2025-07-23T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 4,
        who_you_are: ['Detail-oriented', 'Analytical', 'Collaborative'],
        nice_to_haves: ['Experience with Selenium', 'Agile methodology'],
        perks_benefits: {
          health_coverage: 'Health insurance',
          paid_time_off: '20 days PTO',
          learning_stipend: '$1,500 learning budget',
        },
        level: 'entry level',
        tags: ['engineering', 'technology'],
      },
      {
        company_id:
          companies.find((c) => c.name === 'Zapier')?.id || companies[23].id,
        created_by: employerUsers[23].id,
        title: 'Growth Marketer',
        description: 'Drive growth strategies for Zapier in Sydney, Australia.',
        responsibility: [
          'Develop growth campaigns',
          'Analyze metrics',
          'Collaborate with product teams',
        ],
        qualification: '3+ years in growth marketing',
        job_type: 'full-time',
        skill_required: 'Growth Hacking, Analytics, Marketing',
        salary_range: '$1500 - $2000',
        location: 'Sydney, Australia',
        capacity: 10,
        posted_at: '2025-06-24T00:00:00Z',
        expired_date: '2025-07-24T00:00:00Z',
        is_visible: true,
        views: 0,
        applicant_applied: 3,
        who_you_are: ['Data-driven', 'Creative', 'Strategic'],
        nice_to_haves: ['Experience with SaaS', 'SEO expertise'],
        perks_benefits: {
          health_coverage: 'Comprehensive health insurance',
          remote_work: 'Remote-first culture',
          professional_development: '$2,000 learning stipend',
        },
        level: 'junior',
        tags: ['marketing'],
      },
      // {
      //   company_id:
      //     companies.find((c) => c.name === 'Slack')?.id || companies[24].id,
      //   created_by: employerUsers[24].id,
      //   title: 'Support Specialist',
      //   description: 'Provide customer support for Slack in Lisbon, Portugal.',
      //   responsibility: [
      //     'Handle support tickets',
      //     'Assist users',
      //     'Collaborate with product teams',
      //   ],
      //   qualification: '2+ years in customer support',
      //   job_type: 'full-time',
      //   skill_required: 'Customer Service, Communication, CRM',
      //   salary_range: '$500 - $1000',
      //   location: 'Lisbon, Portugal',
      //   capacity: 6,
      //   posted_at: '2025-06-25T00:00:00Z',
      //   expired_date: '2025-07-25T00:00:00Z',
      //   is_visible: true,
      //   views: 0,
      //   applicant_applied: 2,
      //   who_you_are: ['Empathetic', 'Communicative', 'Organized'],
      //   nice_to_haves: ['Experience with Zendesk', 'Multilingual'],
      //   perks_benefits: {
      //     health_coverage: 'Health insurance',
      //     flexible_hours: 'Flexible schedule',
      //     remote_work: 'Fully remote',
      //   },
      //   level: 'entry level',
      //   tags: ['sales'],
      // },
      // {
      //   company_id:
      //     companies.find((c) => c.name === 'Klarna')?.id || companies[25].id,
      //   created_by: employerUsers[25].id,
      //   title: 'Data Analyst',
      //   description:
      //     'Analyze data to drive insights for Klarna in Stockholm, Sweden.',
      //   responsibility: [
      //     'Analyze datasets',
      //     'Create reports',
      //     'Collaborate with stakeholders',
      //   ],
      //   qualification: '3+ years in data analysis',
      //   job_type: 'full-time',
      //   skill_required: 'SQL, Python, Data Visualization',
      //   salary_range: '$1500 - $2000',
      //   location: 'Stockholm, Sweden',
      //   capacity: 10,
      //   posted_at: '2025-06-26T00:00:00Z',
      //   expired_date: '2025-07-26T00:00:00Z',
      //   is_visible: true,
      //   views: 0,
      //   applicant_applied: 7,
      //   who_you_are: ['Analytical', 'Detail-oriented', 'Collaborative'],
      //   nice_to_haves: [
      //     'Experience with Tableau',
      //     'Machine learning knowledge',
      //   ],
      //   perks_benefits: {
      //     health_coverage: 'Comprehensive health insurance',
      //     paid_time_off: '25 days PTO',
      //     wellness_program: 'Wellness stipend',
      //   },
      //   level: 'junior',
      //   tags: ['business', 'technology'],
      // },
      // {
      //   company_id:
      //     companies.find((c) => c.name === 'Adobe')?.id || companies[26].id,
      //   created_by: employerUsers[26].id,
      //   title: 'Motion Designer',
      //   description: 'Create motion graphics for Adobe in Tokyo, Japan.',
      //   responsibility: [
      //     'Design animations',
      //     'Collaborate with creative teams',
      //     'Ensure brand consistency',
      //   ],
      //   qualification: '3+ years in motion design',
      //   job_type: 'full-time',
      //   skill_required: 'After Effects, Premiere Pro, Animation',
      //   salary_range: '$1500 - $2000',
      //   location: 'Tokyo, Japan',
      //   capacity: 8,
      //   posted_at: '2025-06-27T00:00:00Z',
      //   expired_date: '2025-07-27T00:00:00Z',
      //   is_visible: true,
      //   views: 0,
      //   applicant_applied: 2,
      //   who_you_are: ['Creative', 'Detail-oriented', 'Collaborative'],
      //   nice_to_haves: ['Experience with 3D animation', 'Storyboarding skills'],
      //   perks_benefits: {
      //     health_coverage: 'Health and vision insurance',
      //     flexible_hours: 'Flexible work hours',
      //     professional_development: '$2,000 learning stipend',
      //   },
      //   level: 'junior',
      //   tags: ['design'],
      // },
      // {
      //   company_id:
      //     companies.find((c) => c.name === 'LinkedIn')?.id || companies[27].id,
      //   created_by: employerUsers[27].id,
      //   title: 'Tech Recruiter',
      //   description: 'Recruit top talent for LinkedIn in Dublin, Ireland.',
      //   responsibility: [
      //     'Source candidates',
      //     'Conduct interviews',
      //     'Collaborate with hiring managers',
      //   ],
      //   qualification: '3+ years in technical recruiting',
      //   job_type: 'full-time',
      //   skill_required: 'Recruiting, HR, Communication',
      //   salary_range: '$1500 - $2000',
      //   location: 'Dublin, Ireland',
      //   capacity: 9,
      //   posted_at: '2025-06-28T00:00:00Z',
      //   expired_date: '2025-07-28T00:00:00Z',
      //   is_visible: true,
      //   views: 0,
      //   applicant_applied: 6,
      //   who_you_are: ['Communicative', 'Organized', 'Strategic'],
      //   nice_to_haves: [
      //     'Experience with tech hiring',
      //     'Knowledge of ATS systems',
      //   ],
      //   perks_benefits: {
      //     health_coverage: 'Comprehensive health insurance',
      //     paid_time_off: '25 days PTO',
      //     team_retreats: 'Annual team retreats',
      //   },
      //   level: 'junior',
      //   tags: ['hr'],
      // },
      // {
      //   company_id:
      //     companies.find((c) => c.name === 'Spotify')?.id || companies[28].id,
      //   created_by: employerUsers[28].id,
      //   title: 'Mobile Developer',
      //   description: 'Develop mobile applications for Spotify in Oslo, Norway.',
      //   responsibility: [
      //     'Build mobile apps',
      //     'Optimize performance',
      //     'Collaborate with designers',
      //   ],
      //   qualification: '4+ years in mobile development',
      //   job_type: 'full-time',
      //   skill_required: 'Swift, Kotlin, Mobile Development',
      //   salary_range: '$3000 or above',
      //   location: 'Oslo, Norway',
      //   capacity: 10,
      //   posted_at: '2025-06-29T00:00:00Z',
      //   expired_date: '2025-07-29T00:00:00Z',
      //   is_visible: true,
      //   views: 0,
      //   applicant_applied: 5,
      //   who_you_are: ['Technical', 'Detail-oriented', 'Collaborative'],
      //   nice_to_haves: ['Experience with React Native', 'UI/UX knowledge'],
      //   perks_benefits: {
      //     health_coverage: 'Comprehensive health insurance',
      //     stock_options: 'Equity package',
      //     remote_work: 'Hybrid work options',
      //   },
      //   level: 'senior level',
      //   tags: ['engineering', 'technology'],
      // },
      // {
      //   company_id:
      //     companies.find((c) => c.name === 'DeepMind')?.id || companies[29].id,
      //   created_by: employerUsers[29].id,
      //   title: 'AI Research Intern',
      //   description: 'Support AI research projects for DeepMind in London, UK.',
      //   responsibility: [
      //     'Assist in AI research',
      //     'Analyze datasets',
      //     'Collaborate with researchers',
      //   ],
      //   qualification: 'Pursuing PhD or Master’s in AI/ML',
      //   job_type: 'internship',
      //   skill_required: 'Python, TensorFlow, Machine Learning',
      //   salary_range: '$500 - $1000',
      //   location: 'London, UK',
      //   capacity: 10,
      //   posted_at: '2025-06-30T00:00:00Z',
      //   expired_date: '2025-07-30T00:00:00Z',
      //   is_visible: true,
      //   views: 0,
      //   applicant_applied: 10,
      //   who_you_are: ['Curious', 'Analytical', 'Collaborative'],
      //   nice_to_haves: ['Published research', 'Experience with PyTorch'],
      //   perks_benefits: {
      //     health_coverage: 'Partial health coverage',
      //     learning_stipend: '$1,000 learning budget',
      //   },
      //   level: 'entry level',
      //   tags: ['technology'],
      // },
    ];

    // Save jobs to the database
    const savedJobs: Job[] = [];
    for (const jobData of jobs) {
      if (!jobData.company_id) {
        console.warn(`Skipping job "${jobData.title}" due to missing company.`);
        continue;
      }
      const job = this.jobRepository.create({
        company_id: jobData.company_id,
        created_by: jobData.created_by,
        title: jobData.title,
        description: jobData.description,
        responsibility: jobData.responsibility,
        qualification: jobData.qualification,
        job_type: jobData.job_type,
        skill_required: jobData.skill_required,
        salary_range: jobData.salary_range,
        location: jobData.location,
        capacity: jobData.capacity,
        posted_at: jobData.posted_at,
        expired_date: jobData.expired_date,
        is_visible: jobData.is_visible,
        views: jobData.views,
        applicant_applied: jobData.applicant_applied,
        who_you_are: jobData.who_you_are,
        nice_to_haves: jobData.nice_to_haves,
        perks_benefits: jobData.perks_benefits,
        level: jobData.level,
        tags: jobData.tags,
      });

      const saved = await this.jobRepository.save(job);
      savedJobs.push(saved);
    }

    console.log(`✅ Seeded ${savedJobs.length} jobs successfully.`);

    return savedJobs;
  }
}